---
title: "Identify the location where the gene event happened"
author: "Jimmy Zhong"
date: "5/16/2023"
output: html_document
---
## commands to get the documents required
```{bash}
# first get bayestraits log file: /researchdrive/SpaceHogs_shared/BT_JsNewToL/Trial22.Log.txt
bayestraits_log="Trial22.Log.txt"

grep $'\tNode' $bayestraits_log | head -n -1 > bayesTraits_species_tree_mapping.txt

# run MCMC_stationarity_confidence.Rmd first to get BT_node_origin.csv
```

## Jimmy's ibaray set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source("./events_location_utils.R")

init_env()
BT_nodes_origin = read.csv("BT_node_origin.csv")

bayesTraits_node_coding = get_BT_coding()
leaves_origin = read.delim("leaves_origin.txt", col.names = c("species", "origin")) %>%
  filter(origin %in% state_vec_short)
ecceTERA_node_coding = read.csv("leaves_of_ecceTERA_interal_nodes.csv")

BT_nodes_origin_leaves = merge(BT_nodes_origin, bayesTraits_node_coding, by = "BT_node")
```

## Given an event date file, find the location (probability) in which the event happens.
```{r}
event_date_file = paste0(src_ecceTERA, "/COG1348_symmetric.events_event_dates.txt")

rest = c("left.date", "right.date", "midpoint.date")
merged_cols = colnames(BT_nodes_origin_leaves)[1:(ncol(BT_nodes_origin_leaves)-1)]
l_prob = paste0("left.", merged_cols)
r_prob = paste0("right.", merged_cols)

merge_internal_nodes = function(df) {
  df = merge(df, ecceTERA_node_coding, on = "ecceTERA_node")
  df = merge(df, BT_nodes_origin_leaves, on = "leaves_below")
  df = subset(df, select = -c(leaves_below))
  return(df)
}

merge_leaves = function(df) {
  df = merge(df, leaves_origin, by.x = "ecceTERA_node", by.y = "species")
  df = df %>% mutate(
    BT_node = ecceTERA_node,
    leaves_count = 0)
  return(df)
}

get_event_location = function(event_date_file) {
  COG = str_match(event_date_file, "COG\\d+")[1]
  outfile = sprintf("%s_location_merged_events/%s-events-location.tsv", clock_model, COG)

  tmp = read.delim(event_date_file, na.strings = "?") %>%
    filter(right.node != "UNSAMPLED")
  
  print(sprintf("I should end up with -- %d -- events for %s", nrow(tmp), COG))
  
  # merging left.node
  colnames(tmp) = c(c("event", "ecceTERA_node", "right.node"), rest)
  tmp = merge_internal_nodes(tmp)
  
  # merging right.node
  colnames(tmp) = c(c("left.node", "event", "ecceTERA_node"), rest, l_prob)
  tmp_right_internal = suppressWarnings(filter(tmp, !is.na(as.numeric(ecceTERA_node))))
  tmp_right_leaves = suppressWarnings(filter(tmp, is.na(as.numeric(ecceTERA_node))))
  
  tmp_right_internal = merge_internal_nodes(tmp_right_internal)
  tmp_right_leaves = merge_leaves(tmp_right_leaves)[colnames(tmp_right_internal)]

  event_date_location = rbind(tmp_right_internal, tmp_right_leaves)
  colnames(event_date_location) = c(c("right.node", "left.node", "event"), rest, l_prob, r_prob)

  event_date_location = event_date_location %>% mutate(
    left.origin = str_replace_all(left.origin, state_map),
    right.origin = str_replace_all(right.origin, state_map))

  print(sprintf("In fact, now I have -- %d -- events", nrow(event_date_location)))
  if (nrow(event_date_location) == 0) {
    print("event_data_location dataframe is empty, not writing anything")
  } else {
    print(sprintf("Write file to: %s", outfile))
    write.table(event_date_location, file=outfile, sep = "\t", row.names=FALSE)
  }
  return(outfile)
}

outfile = get_event_location(event_date_file)
```

## Running through all the event files
```{r}
all_event_files = list.files(path = src_ecceTERA, pattern = "*_symmetric.events_event_dates.txt")
merged_files = lapply(paste(src_ecceTERA, all_event_files, sep = "/"), get_event_location)
out_vec = unlist(merged_files)
```

## analyze the event location output matched to genes
```{r}
merged_f = read.csv(out_vec[1])

get_location_state = function(df, target_cols, threshold = 0.6) {
  res_list = apply(df[target_cols],  1, function (row) {
    bool = row[target_cols] > threshold
    if (sum(bool) == 0) {
      return("multi-origin")
    } else {
      return(names(row)[bool])
    }
  })
  return(str_replace_all(unlist(res_list), "right.|left.", ""))
}

merged_f$left_loc = get_location_state(merged_f, l_prob[2:(length(l_prob) - 1)])
merged_f$right_loc = get_location_state(merged_f, r_prob[2:(length(r_prob) - 1)])

defined_origins = merged_f %>%
  filter(! (left_loc == "multi-origin" | right_loc == "multi-origin"))

```
